import {
  AlignLeft,
  Box,
  Calendar,
  Captions,
  CheckCircle2,
  CircleDollarSign,
  CreditCard,
  GalleryHorizontal,
  Grid3x3,
  HelpCircle,
  Image as ImageIcon,
  Layers,
  Layout,
  LayoutGrid,
  LayoutPanelLeft,
  Megaphone,
  MessageCircle,
  Minus,
  MousePointerClick,
  Navigation,
  Phone,
  PlayCircle,
  Quote,
  ScrollText,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Star,
  Tag,
  Timer,
  TrendingUp,
  Type,
  Users,
  Video,
  type LucideIcon,
} from 'lucide-react';
import type { BlockType } from '@eclick-active/shared';

export const BLOCK_ICONS: Record<BlockType, LucideIcon> = {
  // Layout
  hero: Layers,
  hero_video: Video,
  section: LayoutPanelLeft,
  two_columns: LayoutGrid,
  three_columns: Grid3x3,
  // Conteúdo
  heading: Type,
  text: AlignLeft,
  image: ImageIcon,
  video: PlayCircle,
  gallery: GalleryHorizontal,
  benefits: Sparkles,
  features: CheckCircle2,
  stats: TrendingUp,
  testimonials: Quote,
  faq: HelpCircle,
  about: ScrollText,
  team: Users,
  timeline: Layers,
  comparison: Layout,
  countdown: Timer,
  banner: Megaphone,
  divider: Minus,
  spacer: Box,
  custom_html: Captions,
  // Conversão
  cta: MousePointerClick,
  form: ScrollText,
  whatsapp_button: MessageCircle,
  booking: Calendar,
  // Loja
  product_grid: ShoppingBag,
  product_featured: Star,
  product_carousel: ShoppingBag,
  cart: ShoppingCart,
  checkout: CreditCard,
  pricing_table: CircleDollarSign,
  // Estrutura
  navbar: Navigation,
  footer: AlignLeft,
  floating_cta: Phone,
};

export const BLOCK_LABELS: Record<BlockType, string> = {
  hero: 'Hero',
  hero_video: 'Hero com Vídeo',
  section: 'Seção',
  two_columns: 'Duas Colunas',
  three_columns: 'Três Colunas',
  heading: 'Título',
  text: 'Texto',
  image: 'Imagem',
  video: 'Vídeo',
  gallery: 'Galeria',
  benefits: 'Benefícios',
  features: 'Features',
  stats: 'Estatísticas',
  testimonials: 'Depoimentos',
  faq: 'FAQ',
  about: 'Sobre',
  team: 'Equipe',
  timeline: 'Timeline',
  comparison: 'Comparação',
  countdown: 'Countdown',
  banner: 'Banner',
  divider: 'Divisor',
  spacer: 'Espaço',
  custom_html: 'HTML',
  cta: 'CTA',
  form: 'Formulário',
  whatsapp_button: 'Botão WhatsApp',
  booking: 'Agendamento',
  product_grid: 'Grid de Produtos',
  product_featured: 'Produto Destaque',
  product_carousel: 'Carrossel',
  cart: 'Carrinho',
  checkout: 'Checkout',
  pricing_table: 'Tabela de Preços',
  navbar: 'Navbar',
  footer: 'Footer',
  floating_cta: 'CTA Flutuante',
};

export const BLOCK_CATEGORIES: { name: string; icon: string; types: BlockType[] }[] = [
  {
    name: 'Layout',
    icon: '📐',
    types: ['hero', 'hero_video', 'section', 'two_columns', 'three_columns'],
  },
  {
    name: 'Conteúdo',
    icon: '📝',
    types: [
      'heading',
      'text',
      'image',
      'video',
      'gallery',
      'benefits',
      'features',
      'stats',
      'testimonials',
      'faq',
      'about',
      'team',
      'timeline',
      'comparison',
      'countdown',
      'banner',
    ],
  },
  {
    name: 'Conversão',
    icon: '🎯',
    types: ['cta', 'form', 'whatsapp_button', 'booking'],
  },
  {
    name: 'Loja',
    icon: '🛍️',
    types: [
      'product_grid',
      'product_featured',
      'product_carousel',
      'cart',
      'checkout',
      'pricing_table',
    ],
  },
  {
    name: 'Estrutura',
    icon: '🧱',
    types: ['navbar', 'footer', 'floating_cta', 'divider', 'spacer', 'custom_html'],
  },
];
